spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${POSTGRES_DRIVER}

#cloud configuration
eureka:
  client:
    service-url:
      defaultZone: ${API_CORE_EJERCITO_STATISTICS_EUREKA_MICROSERVICE}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}